# Generated by Django 3.0.8 on 2020-07-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=250)),
                ('property_description', models.CharField(max_length=500)),
                ('property_location', models.CharField(max_length=250)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bedroom_desc', models.CharField(max_length=250)),
                ('bathroom_desc', models.CharField(max_length=250)),
                ('toilet_desc', models.CharField(max_length=150)),
                ('property_image', models.ImageField(default='', upload_to='images')),
            ],
            options={
                'verbose_name': 'Properties',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
