# Generated by Django 3.0.8 on 2020-07-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('01', 'RENT'), ('02', 'LEASE'), ('03', 'PURCHASE')], max_length=250),
        ),
    ]
