# Generated by Django 3.0.8 on 2020-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_backend', '0002_auto_20200722_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
